print(" Diffie-Hellman 协议验证")
print("yA = xa^ya = m (mod x) yB = xb^yb = n (mod x)")
xa = int(input("请输入xa："))
ya = int(input("请输入ya："))
m = int(input("请输入m："))
x = int(input("请输入x："))
xb = int(input("请输入xb："))
yb = int(input("请输入yb："))
n = int(input("请输入n："))
print("K值为 " + str(n) + "^" + str(ya) + "≡" + str(n**ya%x))
print("A 验证 " + str(n) + "^" + str(ya) + "≡" + str(n**ya%x) + "(mod " + str(x) + ")")
print("A 验证 " + str(m) + "^" + str(yb) + "≡" + str(m**yb%x) + "(mod " + str(x) + ")")